### ISSUE TITLE
Where are you getting the module.dll from?

### ISSUE THREAD

**Issue by ItsJokerZz** [ItzzExcel/LInjectorUpdater#1]
Where is the module.dll coming from each update?
Fluxus's location? If so what's the location?

**Comment by depthso** [comment]
The JJSploit modules are uploaded to https://github.com/WeAreDevs-Official/WeAreDevs-Official.github.io

**Comment by ItzzExcel** [comment]
> Where is the module.dll coming from each update?
> Fluxus's location? If so what's the location?

This module is the Vega X module. I had to use this due to inactivity in JJSploit Module.
